version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: bibliotecadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bibliotecadb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_biblioteca:/var/lib/mysql


volumes:
  mysql_data_biblioteca:
