"""Agregar campo is_active a Loan

Revision ID: 1aee1a6d12a0
Revises: 39af27c0dbfb
Create Date: 2025-06-10 12:06:29.539178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aee1a6d12a0'
down_revision = '39af27c0dbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('correo'))
        batch_op.drop_index(batch_op.f('numero_identificacion'))

    op.drop_table('users')
    op.drop_table('loans')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('isbn'))

    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('autor', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('editorial', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('anio_publicacion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('cantidad_disponible', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('isbn'), ['isbn'], unique=True)

    op.create_table('loans',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('libro_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_prestamo', sa.DATE(), nullable=False),
    sa.Column('fecha_devolucion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['books.id'], name=op.f('loans_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('loans_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('numero_identificacion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('rol_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contrasena', mysql.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('users_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('numero_identificacion'), ['numero_identificacion'], unique=True)
        batch_op.create_index(batch_op.f('correo'), ['correo'], unique=True)

    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
